"""empty message

Revision ID: 1b175b82cee
Revises: 3c75c74bb94
Create Date: 2015-11-08 14:06:28.235808

"""

# revision identifiers, used by Alembic.
revision = '1b175b82cee'
down_revision = '3c75c74bb94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('is_current', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'is_current')
    ### end Alembic commands ###
