"""empty message

Revision ID: 1f952551533
Revises: 53525d1450a
Create Date: 2015-11-07 23:03:51.647356

"""

# revision identifiers, used by Alembic.
revision = '1f952551533'
down_revision = '53525d1450a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('paused_until', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'paused_until')
    ### end Alembic commands ###
