"""empty message

Revision ID: 201dda3f23e
Revises: 48e6d548f0f
Create Date: 2015-11-07 15:01:10.159383

"""

# revision identifiers, used by Alembic.
revision = '201dda3f23e'
down_revision = '48e6d548f0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speakers', 'number')
    ### end Alembic commands ###
