"""empty message

Revision ID: 497c76393f9
Revises: c14363cf9b
Create Date: 2015-11-07 21:39:34.419696

"""

# revision identifiers, used by Alembic.
revision = '497c76393f9'
down_revision = 'c14363cf9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topics_index_key', 'topics', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('topics_index_key', 'topics', ['index'])
    ### end Alembic commands ###
