"""empty message

Revision ID: 53525d1450a
Revises: 497c76393f9
Create Date: 2015-11-07 22:26:09.145955

"""

# revision identifiers, used by Alembic.
revision = '53525d1450a'
down_revision = '497c76393f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('paused', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'paused')
    ### end Alembic commands ###
