"""empty message

Revision ID: 546e34fac4
Revises: 1b175b82cee
Create Date: 2015-11-11 16:31:09.815812

"""

# revision identifiers, used by Alembic.
revision = '546e34fac4'
down_revision = '1b175b82cee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speakers', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statements', 'speaker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('statements', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('topics', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statements', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('statements', 'speaker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('speakers', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
