"""empty message

Revision ID: 68688a3014
Revises: None
Create Date: 2015-10-02 17:36:48.851931

"""

# revision identifiers, used by Alembic.
revision = '68688a3014'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('roles', sa.PickleType(), nullable=True),
    sa.Column('temp_key', sa.String(), nullable=True),
    sa.Column('temp_key_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('insertion_time', sa.DateTime(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.id'], ),
    sa.ForeignKeyConstraint(['speaker'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    op.drop_table('speakers')
    op.drop_table('users')
    op.drop_table('events')
    ### end Alembic commands ###
