"""empty message

Revision ID: bdf979c44e
Revises: 1f952551533
Create Date: 2015-11-08 11:21:07.739141

"""

# revision identifiers, used by Alembic.
revision = 'bdf979c44e'
down_revision = '1f952551533'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('is_meta', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'is_meta')
    ### end Alembic commands ###
