"""empty message

Revision ID: c14363cf9b
Revises: 201dda3f23e
Create Date: 2015-11-07 20:59:17.755968

"""

# revision identifiers, used by Alembic.
revision = 'c14363cf9b'
down_revision = '201dda3f23e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('index', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'topics', ['index'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_column('topics', 'index')
    ### end Alembic commands ###
